name: merchant_gerbook_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  after_layout: ^1.2.0
  blurrycontainer: ^2.1.0
  camera: ^0.11.2
  cookie_jar: ^4.0.8
  dio: ^5.9.0
  dio_cookie_manager: ^3.3.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.9.1
  flutter_form_builder: ^10.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  flutter_widget_from_html: ^0.17.1
  form_builder_validators: ^11.2.0
  get_it: ^8.2.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  pinput: ^5.0.2
  provider: ^6.1.5+1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.5.3
  signature: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svg/
    - assets/